# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.springframework.boot:spring-boot-starter-web"
        version: ">= 2.4.1"  # Allow updates equal to or greater than version 2.4.0
      - dependency-name: "com.oracle.database.jdbc:ojdbc8"
        version: ">= 21.6.0.0"  # Allow updates equal to or greater than version 21.6.0.0
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-data-jpa"
        versions: ["2.7.13"]  # Ignore updates for version 2.7.13 of spring-boot-starter-data-jpa
